/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Serializer for BusinessAddress model. Used for merchant and shipping addresses.
 *
 * @param id 
 * @param address 
 * @param cityName 
 * @param stateName 
 * @param createdAt 
 * @param modifiedAt 
 * @param postalCode 
 * @param districtId 
 * @param districtName 
 * @param longitude 
 * @param latitude 
 * @param buildingNumber 
 * @param unit 
 * @param receiverName 
 * @param receiverPhone 
 * @param isAccurate 
 * @param isActive 
 */


data class BusinessAddress (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "city_name")
    val cityName: kotlin.String,

    @Json(name = "state_name")
    val stateName: kotlin.String,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "modified_at")
    val modifiedAt: java.time.OffsetDateTime,

    @Json(name = "postal_code")
    val postalCode: kotlin.String? = null,

    @Json(name = "district_id")
    val districtId: kotlin.Int? = null,

    @Json(name = "district_name")
    val districtName: kotlin.String? = null,

    @Json(name = "longitude")
    val longitude: java.math.BigDecimal? = null,

    @Json(name = "latitude")
    val latitude: java.math.BigDecimal? = null,

    @Json(name = "building_number")
    val buildingNumber: kotlin.String? = null,

    @Json(name = "unit")
    val unit: kotlin.String? = null,

    @Json(name = "receiver_name")
    val receiverName: kotlin.String? = null,

    @Json(name = "receiver_phone")
    val receiverPhone: kotlin.String? = null,

    @Json(name = "is_accurate")
    val isAccurate: kotlin.Boolean? = null,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null

) {


}

