/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * * `User is not authenticated.` - کاربر تأیید هویت نشده است. * `Order not found.` - Order not found. * `Order is not in a state where shipping can be selected.` - سفارش در وضعیتی نیست که بتوان روش ارسال را انتخاب کرد. * `Order is not in a state where packing can be selected.` - سفارش در وضعیتی نیست که بتوان بسته‌بندی را انتخاب کرد. * `Failed to initiate refund. Please try again later.` - عملیات بازپرداخت ناموفق بود. لطفاً بعداً دوباره امتحان کنید. * `Order is expired or cancelled.` - سفارش منقضی‌شده یا لغو‌شده است. * `Invalid request origin.` - Invalid request origin. * `Digi Express shipping method not found.` - روش ارسال دیجی اکسپرس یافت نشد. * `Order address not found.` - آدرس سفارش یافت نشد. * `Failed to fetch Digi Express shipping time window options.` - دریافت گزینه‌های بازه زمانی ارسال دیجی اکسپرس ناموفق بود. * `Address ID not found.` - Address ID not found. * `Failed to cancel shipment.` - خطا در کنسل کردن مرسوله. * `Failed to cancel shipment in third party service.` - خطا در کنسل کردن مرسوله از سمت سرویس خارجی. * `Shipment not found.` - Shipment not found. * `Selected shipping method is not eligible for cancellation.` - Selected shipping method is not eligible for cancellation. * `DigiExpress shipment is not in cancelable in this state` - مرسوله دیجی‌اکسپرس در این وضعیت قابل کنسل شدن نیست. * `DigiExpress shipment is not in reviveable in this state` - مرسوله دیجی‌اکسپرس در این وضعیت قابل ارسال مجدد نیست. * `Failed to revive shipment in third party service.` - Failed to revive shipment in third party service. * `Selected shipping method is not eligible for revival.` - Selected shipping method is not eligible for revival.
 *
 * Values: User_is_not_authenticatedPeriod,Order_not_foundPeriod,Order_is_not_in_a_state_where_shipping_can_be_selectedPeriod,Order_is_not_in_a_state_where_packing_can_be_selectedPeriod,Failed_to_initiate_refundPeriod_Please_try_again_laterPeriod,Order_is_expired_or_cancelledPeriod,Invalid_request_originPeriod,Digi_Express_shipping_method_not_foundPeriod,Order_address_not_foundPeriod,Failed_to_fetch_Digi_Express_shipping_time_window_optionsPeriod,Address_ID_not_foundPeriod,Failed_to_cancel_shipmentPeriod,Failed_to_cancel_shipment_in_third_party_servicePeriod,Shipment_not_foundPeriod,Selected_shipping_method_is_not_eligible_for_cancellationPeriod,DigiExpress_shipment_is_not_in_cancelable_in_this_state,DigiExpress_shipment_is_not_in_reviveable_in_this_state,Failed_to_revive_shipment_in_third_party_servicePeriod,Selected_shipping_method_is_not_eligible_for_revivalPeriod
 */

@JsonClass(generateAdapter = false)
enum class ErrorEnum(val value: kotlin.String) {

    @Json(name = "User is not authenticated.")
    User_is_not_authenticatedPeriod("User is not authenticated."),

    @Json(name = "Order not found.")
    Order_not_foundPeriod("Order not found."),

    @Json(name = "Order is not in a state where shipping can be selected.")
    Order_is_not_in_a_state_where_shipping_can_be_selectedPeriod("Order is not in a state where shipping can be selected."),

    @Json(name = "Order is not in a state where packing can be selected.")
    Order_is_not_in_a_state_where_packing_can_be_selectedPeriod("Order is not in a state where packing can be selected."),

    @Json(name = "Failed to initiate refund. Please try again later.")
    Failed_to_initiate_refundPeriod_Please_try_again_laterPeriod("Failed to initiate refund. Please try again later."),

    @Json(name = "Order is expired or cancelled.")
    Order_is_expired_or_cancelledPeriod("Order is expired or cancelled."),

    @Json(name = "Invalid request origin.")
    Invalid_request_originPeriod("Invalid request origin."),

    @Json(name = "Digi Express shipping method not found.")
    Digi_Express_shipping_method_not_foundPeriod("Digi Express shipping method not found."),

    @Json(name = "Order address not found.")
    Order_address_not_foundPeriod("Order address not found."),

    @Json(name = "Failed to fetch Digi Express shipping time window options.")
    Failed_to_fetch_Digi_Express_shipping_time_window_optionsPeriod("Failed to fetch Digi Express shipping time window options."),

    @Json(name = "Address ID not found.")
    Address_ID_not_foundPeriod("Address ID not found."),

    @Json(name = "Failed to cancel shipment.")
    Failed_to_cancel_shipmentPeriod("Failed to cancel shipment."),

    @Json(name = "Failed to cancel shipment in third party service.")
    Failed_to_cancel_shipment_in_third_party_servicePeriod("Failed to cancel shipment in third party service."),

    @Json(name = "Shipment not found.")
    Shipment_not_foundPeriod("Shipment not found."),

    @Json(name = "Selected shipping method is not eligible for cancellation.")
    Selected_shipping_method_is_not_eligible_for_cancellationPeriod("Selected shipping method is not eligible for cancellation."),

    @Json(name = "DigiExpress shipment is not in cancelable in this state")
    DigiExpress_shipment_is_not_in_cancelable_in_this_state("DigiExpress shipment is not in cancelable in this state"),

    @Json(name = "DigiExpress shipment is not in reviveable in this state")
    DigiExpress_shipment_is_not_in_reviveable_in_this_state("DigiExpress shipment is not in reviveable in this state"),

    @Json(name = "Failed to revive shipment in third party service.")
    Failed_to_revive_shipment_in_third_party_servicePeriod("Failed to revive shipment in third party service."),

    @Json(name = "Selected shipping method is not eligible for revival.")
    Selected_shipping_method_is_not_eligible_for_revivalPeriod("Selected shipping method is not eligible for revival.");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ErrorEnum) "$data" else null

        /**
         * Returns a valid [ErrorEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ErrorEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

