/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * * `1` - آنلاین * `2` - BNPL (الان بخر، بعداً پرداخت کن) * `3` - اعتباری * `4` - کیف پول دیجی‌پی * `5` - اقساط پیش‌فرض
 *
 * Values: _1,_2,_3,_4,_5
 */

@JsonClass(generateAdapter = false)
enum class GatewayTypeEnum(val value: kotlin.Int) {

    @Json(name = "1")
    _1(1),

    @Json(name = "2")
    _2(2),

    @Json(name = "3")
    _3(3),

    @Json(name = "4")
    _4(4),

    @Json(name = "5")
    _5(5);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is GatewayTypeEnum) "$data" else null

        /**
         * Returns a valid [GatewayTypeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): GatewayTypeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

