/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import bwdk_sdk.models.OrderStatusEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param message 
 * @param orderUuid 
 * @param status 
 * @param statusDisplay 
 * @param refundReason 
 */


data class MerchantOrderRefundResponse (

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "order_uuid")
    val orderUuid: java.util.UUID,

    @Json(name = "status")
    val status: OrderStatusEnum,

    @Json(name = "status_display")
    val statusDisplay: kotlin.String,

    @Json(name = "refund_reason")
    val refundReason: kotlin.String

) {


}

