/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Serializer for manager view listing PAID_BY_USER orders
 *
 * @param orderUuid 
 * @param merchantOrderId شناسه منحصر به فرد سفارش در سیستم فروشنده
 * @param merchantUniqueId شناسه منحصر به فرد برای پذیرنده برای تأیید سفارش
 * @param paidAt 
 * @param refundsAt 
 */


data class MerchantPaidOrderList (

    @Json(name = "order_uuid")
    val orderUuid: java.util.UUID,

    /* شناسه منحصر به فرد سفارش در سیستم فروشنده */
    @Json(name = "merchant_order_id")
    val merchantOrderId: kotlin.String,

    /* شناسه منحصر به فرد برای پذیرنده برای تأیید سفارش */
    @Json(name = "merchant_unique_id")
    val merchantUniqueId: kotlin.String,

    @Json(name = "paid_at")
    val paidAt: java.time.OffsetDateTime?,

    @Json(name = "refunds_at")
    val refundsAt: java.time.OffsetDateTime?

) {


}

