/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import bwdk_sdk.models.TypeNameEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param typeName نوع ویژگی محصول: رنگ، سایز، گارانتی، وزن یا سایر  * `color` - رنگ * `size` - اندازه * `warranty` - گارانتی * `weight` - وزن * `other` - سایر
 * @param name نام ویژگی (مثلاً 'قرمز' برای رنگ قرمز، 'XL' برای سایز)
 * @param `value` مقدار ویژگی (مثلاً '#FF0000' برای کد رنگ یا مقدار دیگر)
 * @param isColor اگر نوع ویژگی رنگ است درست است، وگرنه غلط
 */


data class Option (

    /* نوع ویژگی محصول: رنگ، سایز، گارانتی، وزن یا سایر  * `color` - رنگ * `size` - اندازه * `warranty` - گارانتی * `weight` - وزن * `other` - سایر */
    @Json(name = "type_name")
    val typeName: TypeNameEnum,

    /* نام ویژگی (مثلاً 'قرمز' برای رنگ قرمز، 'XL' برای سایز) */
    @Json(name = "name")
    val name: kotlin.String,

    /* مقدار ویژگی (مثلاً '#FF0000' برای کد رنگ یا مقدار دیگر) */
    @Json(name = "value")
    val `value`: kotlin.String,

    /* اگر نوع ویژگی رنگ است درست است، وگرنه غلط */
    @Json(name = "is_color")
    val isColor: kotlin.Boolean? = false

) {


}

