/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param firstName 
 * @param lastName 
 * @param phoneNumber 
 * @param nationalIdentityNumber 
 * @param birthDate 
 */


data class OrderUser (

    @Json(name = "first_name")
    val firstName: kotlin.String? = null,

    @Json(name = "last_name")
    val lastName: kotlin.String? = null,

    @Json(name = "phone_number")
    val phoneNumber: kotlin.String? = null,

    @Json(name = "national_identity_number")
    val nationalIdentityNumber: kotlin.String? = null,

    @Json(name = "birth_date")
    val birthDate: java.time.LocalDate? = null

) {


}

