/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import bwdk_sdk.models.OrderItemCreate

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param merchantOrderId شناسه منحصر به فرد این سفارش در سیستم فروشنده
 * @param merchantUniqueId شناسه منحصر به فرد برای تأیید اصالت سفارش
 * @param callbackUrl آدرس وب‌هوک برای دریافت اطلاع رسانی وضعیت پرداخت
 * @param destinationAddress 
 * @param items 
 * @param user 
 * @param referenceCode کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX)
 * @param mainAmount مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان)
 * @param finalAmount مبلغ نهایی: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)
 * @param totalPaidAmount مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)
 * @param discountAmount مبلغ کل تخفیف برای تمام سفارش (به تومان)
 * @param taxAmount مبلغ کل مالیات برای تمام سفارش (به تومان)
 * @param shippingAmount هزینه ارسال برای سفارش (به تومان)
 * @param loyaltyAmount مبلغ تخفیف باشگاه مشتریان/پاداش (به تومان)
 * @param merchant مقدار توسط سیستم جایگذاری می شود
 * @param sourceAddress مقدار توسط سیستم جایگذاری می شود
 * @param reservationExpiredAt مهلت پرداخت (به عنوان Unix timestamp) قبل از اتمام سفارش
 * @param preparationTime Preparation time for the order (in days)
 * @param weight Total Weight of the order (in grams)
 */


data class OrderCreate (

    /* شناسه منحصر به فرد این سفارش در سیستم فروشنده */
    @Json(name = "merchant_order_id")
    val merchantOrderId: kotlin.String,

    /* شناسه منحصر به فرد برای تأیید اصالت سفارش */
    @Json(name = "merchant_unique_id")
    val merchantUniqueId: kotlin.String,

    /* آدرس وب‌هوک برای دریافت اطلاع رسانی وضعیت پرداخت */
    @Json(name = "callback_url")
    val callbackUrl: java.net.URI,

    @Json(name = "destination_address")
    val destinationAddress: kotlin.Any?,

    @Json(name = "items")
    val items: kotlin.collections.List<OrderItemCreate>,

    @Json(name = "user")
    val user: kotlin.Int?,

    /* کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX) */
    @Json(name = "reference_code")
    val referenceCode: kotlin.String,

    /* مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان) */
    @Json(name = "main_amount")
    val mainAmount: kotlin.Int? = null,

    /* مبلغ نهایی: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان) */
    @Json(name = "final_amount")
    val finalAmount: kotlin.Int? = null,

    /* مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان) */
    @Json(name = "total_paid_amount")
    val totalPaidAmount: kotlin.Int? = null,

    /* مبلغ کل تخفیف برای تمام سفارش (به تومان) */
    @Json(name = "discount_amount")
    val discountAmount: kotlin.Int? = null,

    /* مبلغ کل مالیات برای تمام سفارش (به تومان) */
    @Json(name = "tax_amount")
    val taxAmount: kotlin.Int? = null,

    /* هزینه ارسال برای سفارش (به تومان) */
    @Json(name = "shipping_amount")
    val shippingAmount: kotlin.Int? = null,

    /* مبلغ تخفیف باشگاه مشتریان/پاداش (به تومان) */
    @Json(name = "loyalty_amount")
    val loyaltyAmount: kotlin.Int? = null,

    /* مقدار توسط سیستم جایگذاری می شود */
    @Json(name = "merchant")
    val merchant: kotlin.Int? = null,

    /* مقدار توسط سیستم جایگذاری می شود */
    @Json(name = "source_address")
    val sourceAddress: kotlin.Any? = null,

    /* مهلت پرداخت (به عنوان Unix timestamp) قبل از اتمام سفارش */
    @Json(name = "reservation_expired_at")
    val reservationExpiredAt: kotlin.Int? = null,

    /* Preparation time for the order (in days) */
    @Json(name = "preparation_time")
    val preparationTime: kotlin.Int? = 2,

    /* Total Weight of the order (in grams) */
    @Json(name = "weight")
    val weight: kotlin.Double? = null

) {


}

