/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import bwdk_sdk.models.Merchant
import bwdk_sdk.models.OrderItemCreate
import bwdk_sdk.models.OrderStatusEnum
import bwdk_sdk.models.OrderUser
import bwdk_sdk.models.Packing
import bwdk_sdk.models.PaymentOrder
import bwdk_sdk.models.ShippingMethod

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param createdAt 
 * @param orderUuid 
 * @param reservationExpiredAt Unix timestamp تا زمانی که سفارش برای پرداخت رزرو شده است
 * @param merchantOrderId شناسه منحصر به فرد سفارش در سیستم فروشنده
 * @param status 
 * @param statusDisplay 
 * @param mainAmount مجموع قیمت اولیه تمام کالاهای سفارش بدون تخفیف (به تومان)
 * @param finalAmount قیمت نهایی قابل پرداخت توسط مشتری: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)
 * @param totalPaidAmount مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)
 * @param discountAmount مبلغ کل تخفیف اعمال شده بر سفارش (به تومان)
 * @param taxAmount مبلغ کل مالیات برای سفارش (به تومان)
 * @param shippingAmount هزینه ارسال برای سفارش (به تومان)
 * @param loyaltyAmount مقدار تخفیف از برنامه باشگاه مشتریان/پاداش (به تومان)
 * @param callbackUrl آدرسی برای دریافت اطلاع رسانی وضعیت پرداخت پس از تکمیل سفارش
 * @param merchant 
 * @param items 
 * @param sourceAddress 
 * @param destinationAddress 
 * @param selectedShippingMethod 
 * @param shippingSelectedAt 
 * @param addressSelectedAt 
 * @param packingAmount هزینه روش بسته‌بندی انتخاب‌شده (به تومان)
 * @param packingSelectedAt 
 * @param selectedPacking 
 * @param canSelectPacking 
 * @param canSelectShipping 
 * @param canSelectAddress 
 * @param canProceedToPayment 
 * @param isPaid 
 * @param user 
 * @param payment 
 * @param preparationTime Preparation time for the order (in days)
 * @param weight Total weight of the order (in grams)
 * @param selectedShippingData 
 * @param referenceCode کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX)
 * @param promotionDiscountAmount 
 * @param promotionData 
 * @param digipayMarkupAmount Markup amount for the order (in Tomans)
 * @param markupCommissionPercentage Markup commission percentage for the order (in percent)
 * @param previousStatus 
 * @param previousStatusDisplay 
 */


data class OrderDetail (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "order_uuid")
    val orderUuid: java.util.UUID,

    /* Unix timestamp تا زمانی که سفارش برای پرداخت رزرو شده است */
    @Json(name = "reservation_expired_at")
    val reservationExpiredAt: kotlin.Int?,

    /* شناسه منحصر به فرد سفارش در سیستم فروشنده */
    @Json(name = "merchant_order_id")
    val merchantOrderId: kotlin.String,

    @Json(name = "status")
    val status: OrderStatusEnum,

    @Json(name = "status_display")
    val statusDisplay: kotlin.String,

    /* مجموع قیمت اولیه تمام کالاهای سفارش بدون تخفیف (به تومان) */
    @Json(name = "main_amount")
    val mainAmount: kotlin.Int,

    /* قیمت نهایی قابل پرداخت توسط مشتری: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان) */
    @Json(name = "final_amount")
    val finalAmount: kotlin.Int,

    /* مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان) */
    @Json(name = "total_paid_amount")
    val totalPaidAmount: kotlin.Int,

    /* مبلغ کل تخفیف اعمال شده بر سفارش (به تومان) */
    @Json(name = "discount_amount")
    val discountAmount: kotlin.Int,

    /* مبلغ کل مالیات برای سفارش (به تومان) */
    @Json(name = "tax_amount")
    val taxAmount: kotlin.Int,

    /* هزینه ارسال برای سفارش (به تومان) */
    @Json(name = "shipping_amount")
    val shippingAmount: kotlin.Int,

    /* مقدار تخفیف از برنامه باشگاه مشتریان/پاداش (به تومان) */
    @Json(name = "loyalty_amount")
    val loyaltyAmount: kotlin.Int,

    /* آدرسی برای دریافت اطلاع رسانی وضعیت پرداخت پس از تکمیل سفارش */
    @Json(name = "callback_url")
    val callbackUrl: java.net.URI,

    @Json(name = "merchant")
    val merchant: Merchant,

    @Json(name = "items")
    val items: kotlin.collections.List<OrderItemCreate>,

    @Json(name = "source_address")
    val sourceAddress: kotlin.Any?,

    @Json(name = "destination_address")
    val destinationAddress: kotlin.Any?,

    @Json(name = "selected_shipping_method")
    val selectedShippingMethod: ShippingMethod,

    @Json(name = "shipping_selected_at")
    val shippingSelectedAt: java.time.OffsetDateTime?,

    @Json(name = "address_selected_at")
    val addressSelectedAt: java.time.OffsetDateTime?,

    /* هزینه روش بسته‌بندی انتخاب‌شده (به تومان) */
    @Json(name = "packing_amount")
    val packingAmount: kotlin.Int,

    @Json(name = "packing_selected_at")
    val packingSelectedAt: java.time.OffsetDateTime?,

    @Json(name = "selected_packing")
    val selectedPacking: Packing,

    @Json(name = "can_select_packing")
    val canSelectPacking: kotlin.Boolean,

    @Json(name = "can_select_shipping")
    val canSelectShipping: kotlin.Boolean,

    @Json(name = "can_select_address")
    val canSelectAddress: kotlin.Boolean,

    @Json(name = "can_proceed_to_payment")
    val canProceedToPayment: kotlin.Boolean,

    @Json(name = "is_paid")
    val isPaid: kotlin.Boolean,

    @Json(name = "user")
    val user: OrderUser,

    @Json(name = "payment")
    val payment: PaymentOrder,

    /* Preparation time for the order (in days) */
    @Json(name = "preparation_time")
    val preparationTime: kotlin.Int,

    /* Total weight of the order (in grams) */
    @Json(name = "weight")
    val weight: kotlin.Double,

    @Json(name = "selected_shipping_data")
    val selectedShippingData: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX) */
    @Json(name = "reference_code")
    val referenceCode: kotlin.String,

    @Json(name = "promotion_discount_amount")
    val promotionDiscountAmount: kotlin.Double,

    @Json(name = "promotion_data")
    val promotionData: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* Markup amount for the order (in Tomans) */
    @Json(name = "digipay_markup_amount")
    val digipayMarkupAmount: kotlin.Int,

    /* Markup commission percentage for the order (in percent) */
    @Json(name = "markup_commission_percentage")
    val markupCommissionPercentage: kotlin.Int,

    @Json(name = "previous_status")
    val previousStatus: OrderStatusEnum?,

    @Json(name = "previous_status_display")
    val previousStatusDisplay: kotlin.String

) {


}

