/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import bwdk_sdk.models.Option

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name نام کامل محصول شامل تمام مشخصات
 * @param count تعداد واحدهای این کالا در سفارش
 * @param options 
 * @param primaryAmount قیمت اولیه برای هر واحد بدون تخفیف (به تومان)
 * @param amount قیمت نهایی برای تمام واحدها بعد از تخفیف (به تومان)
 * @param discountAmount مبلغ کل تخفیف برای این کالا (به تومان)
 * @param taxAmount مبلغ کل مالیات برای این کالا (به تومان)
 * @param imageLink آدرس تصویر محصول
 * @param preparationTime Preparation time for the item (in days)
 * @param weight Weight of the item (in grams)
 */


data class OrderItemCreate (

    /* نام کامل محصول شامل تمام مشخصات */
    @Json(name = "name")
    val name: kotlin.String,

    /* تعداد واحدهای این کالا در سفارش */
    @Json(name = "count")
    val count: kotlin.Int,

    @Json(name = "options")
    val options: kotlin.collections.List<Option>,

    /* قیمت اولیه برای هر واحد بدون تخفیف (به تومان) */
    @Json(name = "primary_amount")
    val primaryAmount: kotlin.Int? = null,

    /* قیمت نهایی برای تمام واحدها بعد از تخفیف (به تومان) */
    @Json(name = "amount")
    val amount: kotlin.Int? = null,

    /* مبلغ کل تخفیف برای این کالا (به تومان) */
    @Json(name = "discount_amount")
    val discountAmount: kotlin.Int? = null,

    /* مبلغ کل مالیات برای این کالا (به تومان) */
    @Json(name = "tax_amount")
    val taxAmount: kotlin.Int? = null,

    /* آدرس تصویر محصول */
    @Json(name = "image_link")
    val imageLink: java.net.URI? = null,

    /* Preparation time for the item (in days) */
    @Json(name = "preparation_time")
    val preparationTime: kotlin.Int? = 2,

    /* Weight of the item (in grams) */
    @Json(name = "weight")
    val weight: kotlin.Double? = null

) {


}

