/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name نام روش/گزینه بسته‌بندی
 * @param price هزینه بسته بندی به تومان
 */


data class Packing (

    @Json(name = "id")
    val id: kotlin.Int,

    /* نام روش/گزینه بسته‌بندی */
    @Json(name = "name")
    val name: kotlin.String,

    /* هزینه بسته بندی به تومان */
    @Json(name = "price")
    val price: kotlin.Int? = null

) {


}

