/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import bwdk_sdk.models.OrderDetail

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param results 
 * @param next 
 * @param previous 
 */


data class PaginatedOrderDetailList (

    @Json(name = "results")
    val results: kotlin.collections.List<OrderDetail>,

    @Json(name = "next")
    val next: java.net.URI? = null,

    @Json(name = "previous")
    val previous: java.net.URI? = null

) {


}

