/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import bwdk_sdk.models.GatewayTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param finalAmount 
 * @param gatewayType 
 * @param gatewayTypeDisplay 
 * @param paidAt 
 * @param gatewayName 
 * @param invoiceId 
 * @param settlementDate 
 * @param settlementStatus 
 * @param settlementStatusDisplay 
 */


data class PaymentOrder (

    @Json(name = "final_amount")
    val finalAmount: kotlin.Int,

    @Json(name = "gateway_type")
    val gatewayType: GatewayTypeEnum,

    @Json(name = "gateway_type_display")
    val gatewayTypeDisplay: kotlin.String,

    @Json(name = "paid_at")
    val paidAt: kotlin.String,

    @Json(name = "gateway_name")
    val gatewayName: kotlin.String?,

    @Json(name = "invoice_id")
    val invoiceId: kotlin.String?,

    @Json(name = "settlement_date")
    val settlementDate: kotlin.String,

    @Json(name = "settlement_status")
    val settlementStatus: kotlin.Int,

    @Json(name = "settlement_status_display")
    val settlementStatusDisplay: kotlin.String

) {


}

