/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Serializer for refunding an order.
 *
 * @param reason دلیل اختیاری برای بازگرداندن وجه
 */


data class RefundOrder (

    /* دلیل اختیاری برای بازگرداندن وجه */
    @Json(name = "reason")
    val reason: kotlin.String? = null

) {


}

