/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import bwdk_sdk.models.BusinessAddress
import bwdk_sdk.models.DeliveryTimeRangeDisplay
import bwdk_sdk.models.ShippingTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Serializer for shipping method details.
 *
 * @param id 
 * @param name نام روش ارسال
 * @param getShippingTypeDisplay 
 * @param shippingTypeDisplay 
 * @param deliveryTimeDisplay 
 * @param deliveryTimeRangeDisplay 
 * @param inventoryAddress 
 * @param description توضیحات روش ارسال و جزئیات تحویل آن
 * @param shippingType نوع روش ارسال: عادی یا دیجی اکسپرس  * `1` - سایر * `2` - دیجی اکسپرس
 * @param cost هزینه ارسال برای منطقه اولیه (مثلاً تهران) به تومان
 * @param secondaryCost هزینه ارسال برای مناطق دیگر به تومان
 * @param minimumTimeSending حداقل تعداد روزها از تاریخ سفارش تا تحویل
 * @param maximumTimeSending حداکثر تعداد روزها از تاریخ سفارش تا تحویل
 * @param isPayAtDestination Whether the shipping method is pay at destination
 */


data class ShippingMethod (

    @Json(name = "id")
    val id: kotlin.Int,

    /* نام روش ارسال */
    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "get_shipping_type_display")
    val getShippingTypeDisplay: kotlin.String,

    @Json(name = "shipping_type_display")
    val shippingTypeDisplay: kotlin.String,

    @Json(name = "delivery_time_display")
    val deliveryTimeDisplay: kotlin.String,

    @Json(name = "delivery_time_range_display")
    val deliveryTimeRangeDisplay: DeliveryTimeRangeDisplay,

    @Json(name = "inventory_address")
    val inventoryAddress: BusinessAddress,

    /* توضیحات روش ارسال و جزئیات تحویل آن */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* نوع روش ارسال: عادی یا دیجی اکسپرس  * `1` - سایر * `2` - دیجی اکسپرس */
    @Json(name = "shipping_type")
    val shippingType: ShippingTypeEnum? = null,

    /* هزینه ارسال برای منطقه اولیه (مثلاً تهران) به تومان */
    @Json(name = "cost")
    val cost: kotlin.Int? = null,

    /* هزینه ارسال برای مناطق دیگر به تومان */
    @Json(name = "secondary_cost")
    val secondaryCost: kotlin.Int? = null,

    /* حداقل تعداد روزها از تاریخ سفارش تا تحویل */
    @Json(name = "minimum_time_sending")
    val minimumTimeSending: kotlin.Int? = null,

    /* حداکثر تعداد روزها از تاریخ سفارش تا تحویل */
    @Json(name = "maximum_time_sending")
    val maximumTimeSending: kotlin.Int? = null,

    /* Whether the shipping method is pay at destination */
    @Json(name = "is_pay_at_destination")
    val isPayAtDestination: kotlin.Boolean? = null

) {


}

