/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param negativeSettlementDeadline Deadline for settling negative balance
 * @param amount Current wallet balance in Tomans
 */


data class WalletBalance (

    /* Deadline for settling negative balance */
    @Json(name = "negative_settlement_deadline")
    val negativeSettlementDeadline: kotlin.String?,

    /* Current wallet balance in Tomans */
    @Json(name = "amount")
    val amount: kotlin.Int? = null

) {


}

