/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import bwdk_sdk.models.AuthStatusResponse

import com.squareup.moshi.Json

import bwdk_sdk.infrastructure.ApiClient
import bwdk_sdk.infrastructure.ApiResponse
import bwdk_sdk.infrastructure.ClientException
import bwdk_sdk.infrastructure.ClientError
import bwdk_sdk.infrastructure.ServerException
import bwdk_sdk.infrastructure.ServerError
import bwdk_sdk.infrastructure.MultiValueMap
import bwdk_sdk.infrastructure.PartConfig
import bwdk_sdk.infrastructure.RequestConfig
import bwdk_sdk.infrastructure.RequestMethod
import bwdk_sdk.infrastructure.ResponseType
import bwdk_sdk.infrastructure.Success
import bwdk_sdk.infrastructure.toMultiValue

open class SellerProfileManagementApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://bwdk-backend.digify.shop")
        }
    }

    /**
     * GET /merchant/api/v1/auth/status/
     * وضعیت لاگین بودن
     * &lt;div dir&#x3D;\&quot;rtl\&quot; style&#x3D;\&quot;text-align: right;\&quot;&gt;  بررسی وضعیت احراز هویت فروشنده  ## توضیحات  این endpoint برای بررسی اعتبار **API_KEY** فروشنده استفاده می‌شود. اگر کلید معتبر باشد، پاسخ &#x60;is_authenticated: true&#x60; برمی‌گردد. از این endpoint برای تأیید صحت کلید API قبل از شروع عملیات استفاده کنید.  نیاز به **API_KEY** فروشنده دارد (فقط Header لازم است، بدنه درخواست ندارد).  &lt;/div&gt; 
     * @return AuthStatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun merchantApiV1AuthStatusRetrieve() : AuthStatusResponse {
        val localVarResponse = merchantApiV1AuthStatusRetrieveWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AuthStatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /merchant/api/v1/auth/status/
     * وضعیت لاگین بودن
     * &lt;div dir&#x3D;\&quot;rtl\&quot; style&#x3D;\&quot;text-align: right;\&quot;&gt;  بررسی وضعیت احراز هویت فروشنده  ## توضیحات  این endpoint برای بررسی اعتبار **API_KEY** فروشنده استفاده می‌شود. اگر کلید معتبر باشد، پاسخ &#x60;is_authenticated: true&#x60; برمی‌گردد. از این endpoint برای تأیید صحت کلید API قبل از شروع عملیات استفاده کنید.  نیاز به **API_KEY** فروشنده دارد (فقط Header لازم است، بدنه درخواست ندارد).  &lt;/div&gt; 
     * @return ApiResponse<AuthStatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun merchantApiV1AuthStatusRetrieveWithHttpInfo() : ApiResponse<AuthStatusResponse?> {
        val localVariableConfig = merchantApiV1AuthStatusRetrieveRequestConfig()

        return request<Unit, AuthStatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation merchantApiV1AuthStatusRetrieve
     *
     * @return RequestConfig
     */
    fun merchantApiV1AuthStatusRetrieveRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/merchant/api/v1/auth/status/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
