/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.apis.MerchantWalletApi
import bwdk_sdk.models.WalletBalance

class MerchantWalletApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MerchantWalletApi
        //val apiInstance = MerchantWalletApi()

        // to test walletsApiV1WalletBalanceRetrieve
        should("test walletsApiV1WalletBalanceRetrieve") {
            // uncomment below to test walletsApiV1WalletBalanceRetrieve
            //val result : WalletBalance = apiInstance.walletsApiV1WalletBalanceRetrieve()
            //result shouldBe ("TODO")
        }

    }
}
