/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.apis.MerchantOrdersApi
import bwdk_sdk.models.MerchantOrderRefundResponse
import bwdk_sdk.models.OrderCreate
import bwdk_sdk.models.OrderCreateResponse
import bwdk_sdk.models.OrderDetail
import bwdk_sdk.models.OrderError
import bwdk_sdk.models.PaginatedMerchantPaidOrderListList
import bwdk_sdk.models.PaginatedOrderDetailList
import bwdk_sdk.models.RefundOrder
import bwdk_sdk.models.UpdateOrderStatus
import bwdk_sdk.models.VerifyOrder

class MerchantOrdersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MerchantOrdersApi
        //val apiInstance = MerchantOrdersApi()

        // to test orderApiV1CreateOrderCreate
        should("test orderApiV1CreateOrderCreate") {
            // uncomment below to test orderApiV1CreateOrderCreate
            //val orderCreate : OrderCreate =  // OrderCreate | 
            //val result : OrderCreateResponse = apiInstance.orderApiV1CreateOrderCreate(orderCreate)
            //result shouldBe ("TODO")
        }

        // to test orderApiV1ManagerList
        should("test orderApiV1ManagerList") {
            // uncomment below to test orderApiV1ManagerList
            //val cities : kotlin.String = cities_example // kotlin.String | 
            //val createdAt : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | مقدار نشانگر صفحه‌بندی.
            //val orderIds : kotlin.String = orderIds_example // kotlin.String | 
            //val ordering : kotlin.String = ordering_example // kotlin.String | کدام فیلد باید هنگام مرتب‌سازی نتایج استفاده شود.
            //val paymentTypes : kotlin.String = paymentTypes_example // kotlin.String | 
            //val provinces : kotlin.String = provinces_example // kotlin.String | 
            //val referenceCode : kotlin.String = referenceCode_example // kotlin.String | 
            //val search : kotlin.String = search_example // kotlin.String | یک عبارت جستجو.
            //val shippingTypes : kotlin.String = shippingTypes_example // kotlin.String | 
            //val status : kotlin.Int = 56 // kotlin.Int | * `1` - اولیه * `2` - شروع شده * `3` - در انتظار * `4` - در انتظار درگاه * `5` - منقضی شده * `6` - لغو شده * `7` - پرداخت‌شده توسط کاربر * `8` - پرداخت موفیت آمیز نبود * `9` - تأیید شده توسط فروشگاه * `10` - تأیید توسط فروشگاه ناموفق بود * `11` - ناموفق از سوی فروشگاه * `12` - لغوشده توسط فروشگاه * `13` - درخواست بازگشت وجه به مشتری به دلیل درخواست مشتری * `14` - درخواست بازگشت وجه به فروشگاه پس از عدم تأیید توسط فروشگاه * `15` - درخواست بازگشت وجه به مشتری پس از ناموفق بودن توسط فروشگاه * `16` - بازپرداخت به فروشگاه پس از لغو توسط فروشگاه * `17` - بازپرداخت تکمیل شد * `18` - زمان انقضا گذشته است * `19` - تحویل شده * `20` - جمع اوری شده و در حال ارسال
            //val statuses : kotlin.String = statuses_example // kotlin.String | 
            //val todayPickup : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : PaginatedOrderDetailList = apiInstance.orderApiV1ManagerList(cities, createdAt, cursor, orderIds, ordering, paymentTypes, provinces, referenceCode, search, shippingTypes, status, statuses, todayPickup)
            //result shouldBe ("TODO")
        }

        // to test orderApiV1ManagerPaidList
        should("test orderApiV1ManagerPaidList") {
            // uncomment below to test orderApiV1ManagerPaidList
            //val cities : kotlin.String = cities_example // kotlin.String | 
            //val createdAt : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | مقدار نشانگر صفحه‌بندی.
            //val orderIds : kotlin.String = orderIds_example // kotlin.String | 
            //val ordering : kotlin.String = ordering_example // kotlin.String | کدام فیلد باید هنگام مرتب‌سازی نتایج استفاده شود.
            //val paymentTypes : kotlin.String = paymentTypes_example // kotlin.String | 
            //val provinces : kotlin.String = provinces_example // kotlin.String | 
            //val referenceCode : kotlin.String = referenceCode_example // kotlin.String | 
            //val search : kotlin.String = search_example // kotlin.String | یک عبارت جستجو.
            //val shippingTypes : kotlin.String = shippingTypes_example // kotlin.String | 
            //val status : kotlin.Int = 56 // kotlin.Int | * `1` - اولیه * `2` - شروع شده * `3` - در انتظار * `4` - در انتظار درگاه * `5` - منقضی شده * `6` - لغو شده * `7` - پرداخت‌شده توسط کاربر * `8` - پرداخت موفیت آمیز نبود * `9` - تأیید شده توسط فروشگاه * `10` - تأیید توسط فروشگاه ناموفق بود * `11` - ناموفق از سوی فروشگاه * `12` - لغوشده توسط فروشگاه * `13` - درخواست بازگشت وجه به مشتری به دلیل درخواست مشتری * `14` - درخواست بازگشت وجه به فروشگاه پس از عدم تأیید توسط فروشگاه * `15` - درخواست بازگشت وجه به مشتری پس از ناموفق بودن توسط فروشگاه * `16` - بازپرداخت به فروشگاه پس از لغو توسط فروشگاه * `17` - بازپرداخت تکمیل شد * `18` - زمان انقضا گذشته است * `19` - تحویل شده * `20` - جمع اوری شده و در حال ارسال
            //val statuses : kotlin.String = statuses_example // kotlin.String | 
            //val todayPickup : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : PaginatedMerchantPaidOrderListList = apiInstance.orderApiV1ManagerPaidList(cities, createdAt, cursor, orderIds, ordering, paymentTypes, provinces, referenceCode, search, shippingTypes, status, statuses, todayPickup)
            //result shouldBe ("TODO")
        }

        // to test orderApiV1ManagerRefundCreate
        should("test orderApiV1ManagerRefundCreate") {
            // uncomment below to test orderApiV1ManagerRefundCreate
            //val orderUuid : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val refundOrder : RefundOrder =  // RefundOrder | 
            //val result : MerchantOrderRefundResponse = apiInstance.orderApiV1ManagerRefundCreate(orderUuid, refundOrder)
            //result shouldBe ("TODO")
        }

        // to test orderApiV1ManagerRetrieve
        should("test orderApiV1ManagerRetrieve") {
            // uncomment below to test orderApiV1ManagerRetrieve
            //val orderUuid : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : OrderDetail = apiInstance.orderApiV1ManagerRetrieve(orderUuid)
            //result shouldBe ("TODO")
        }

        // to test orderApiV1ManagerUpdateStatusUpdate
        should("test orderApiV1ManagerUpdateStatusUpdate") {
            // uncomment below to test orderApiV1ManagerUpdateStatusUpdate
            //val orderUuid : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val updateOrderStatus : UpdateOrderStatus =  // UpdateOrderStatus | 
            //val result : OrderDetail = apiInstance.orderApiV1ManagerUpdateStatusUpdate(orderUuid, updateOrderStatus)
            //result shouldBe ("TODO")
        }

        // to test orderApiV1ManagerVerifyCreate
        should("test orderApiV1ManagerVerifyCreate") {
            // uncomment below to test orderApiV1ManagerVerifyCreate
            //val orderUuid : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val verifyOrder : VerifyOrder =  // VerifyOrder | 
            //val result : OrderDetail = apiInstance.orderApiV1ManagerVerifyCreate(orderUuid, verifyOrder)
            //result shouldBe ("TODO")
        }

    }
}
