/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.apis.OrderShippingApi
import bwdk_sdk.models.MerchantOrderCancelShipmentResponse
import bwdk_sdk.models.MerchantOrderReviveShipmentResponse
import bwdk_sdk.models.OrderDetail
import bwdk_sdk.models.OrderError
import bwdk_sdk.models.ReviveShipment

class OrderShippingApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderShippingApi
        //val apiInstance = OrderShippingApi()

        // to test orderApiV1ManagerCancelShipmentCreate
        should("test orderApiV1ManagerCancelShipmentCreate") {
            // uncomment below to test orderApiV1ManagerCancelShipmentCreate
            //val orderUuid : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : MerchantOrderCancelShipmentResponse = apiInstance.orderApiV1ManagerCancelShipmentCreate(orderUuid)
            //result shouldBe ("TODO")
        }

        // to test orderApiV1ManagerChangeShippingMethodUpdate
        should("test orderApiV1ManagerChangeShippingMethodUpdate") {
            // uncomment below to test orderApiV1ManagerChangeShippingMethodUpdate
            //val orderUuid : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val orderDetail : OrderDetail =  // OrderDetail | 
            //val result : OrderDetail = apiInstance.orderApiV1ManagerChangeShippingMethodUpdate(orderUuid, orderDetail)
            //result shouldBe ("TODO")
        }

        // to test orderApiV1ManagerReviveShipmentCreate
        should("test orderApiV1ManagerReviveShipmentCreate") {
            // uncomment below to test orderApiV1ManagerReviveShipmentCreate
            //val orderUuid : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val reviveShipment : ReviveShipment =  // ReviveShipment | 
            //val result : MerchantOrderReviveShipmentResponse = apiInstance.orderApiV1ManagerReviveShipmentCreate(orderUuid, reviveShipment)
            //result shouldBe ("TODO")
        }

    }
}
