/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.apis.SellerProfileManagementApi
import bwdk_sdk.models.AuthStatusResponse

class SellerProfileManagementApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SellerProfileManagementApi
        //val apiInstance = SellerProfileManagementApi()

        // to test merchantApiV1AuthStatusRetrieve
        should("test merchantApiV1AuthStatusRetrieve") {
            // uncomment below to test merchantApiV1AuthStatusRetrieve
            //val result : AuthStatusResponse = apiInstance.merchantApiV1AuthStatusRetrieve()
            //result shouldBe ("TODO")
        }

    }
}
