/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.BusinessAddress

class BusinessAddressTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BusinessAddress
        //val modelInstance = BusinessAddress()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `address`
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

        // to test the property `cityName`
        should("test cityName") {
            // uncomment below to test the property
            //modelInstance.cityName shouldBe ("TODO")
        }

        // to test the property `stateName`
        should("test stateName") {
            // uncomment below to test the property
            //modelInstance.stateName shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `modifiedAt`
        should("test modifiedAt") {
            // uncomment below to test the property
            //modelInstance.modifiedAt shouldBe ("TODO")
        }

        // to test the property `postalCode`
        should("test postalCode") {
            // uncomment below to test the property
            //modelInstance.postalCode shouldBe ("TODO")
        }

        // to test the property `districtId`
        should("test districtId") {
            // uncomment below to test the property
            //modelInstance.districtId shouldBe ("TODO")
        }

        // to test the property `districtName`
        should("test districtName") {
            // uncomment below to test the property
            //modelInstance.districtName shouldBe ("TODO")
        }

        // to test the property `longitude`
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

        // to test the property `latitude`
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `buildingNumber`
        should("test buildingNumber") {
            // uncomment below to test the property
            //modelInstance.buildingNumber shouldBe ("TODO")
        }

        // to test the property `unit`
        should("test unit") {
            // uncomment below to test the property
            //modelInstance.unit shouldBe ("TODO")
        }

        // to test the property `receiverName`
        should("test receiverName") {
            // uncomment below to test the property
            //modelInstance.receiverName shouldBe ("TODO")
        }

        // to test the property `receiverPhone`
        should("test receiverPhone") {
            // uncomment below to test the property
            //modelInstance.receiverPhone shouldBe ("TODO")
        }

        // to test the property `isAccurate`
        should("test isAccurate") {
            // uncomment below to test the property
            //modelInstance.isAccurate shouldBe ("TODO")
        }

        // to test the property `isActive`
        should("test isActive") {
            // uncomment below to test the property
            //modelInstance.isActive shouldBe ("TODO")
        }

    }
}
