/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.DeliveryTimeRangeDisplay

class DeliveryTimeRangeDisplayTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeliveryTimeRangeDisplay
        //val modelInstance = DeliveryTimeRangeDisplay()

        // to test the property `minDate`
        should("test minDate") {
            // uncomment below to test the property
            //modelInstance.minDate shouldBe ("TODO")
        }

        // to test the property `maxDate`
        should("test maxDate") {
            // uncomment below to test the property
            //modelInstance.maxDate shouldBe ("TODO")
        }

    }
}
