/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.MerchantOrderCancelShipmentResponse
import bwdk_sdk.models.OrderStatusEnum

class MerchantOrderCancelShipmentResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MerchantOrderCancelShipmentResponse
        //val modelInstance = MerchantOrderCancelShipmentResponse()

        // to test the property `message` - Success message
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `orderUuid` - Order unique identifier
        should("test orderUuid") {
            // uncomment below to test the property
            //modelInstance.orderUuid shouldBe ("TODO")
        }

        // to test the property `status` - Current order status  * `1` - اولیه * `2` - شروع شده * `3` - در انتظار * `4` - در انتظار درگاه * `5` - منقضی شده * `6` - لغو شده * `7` - پرداخت‌شده توسط کاربر * `8` - پرداخت موفیت آمیز نبود * `9` - تأیید شده توسط فروشگاه * `10` - تأیید توسط فروشگاه ناموفق بود * `11` - ناموفق از سوی فروشگاه * `12` - لغوشده توسط فروشگاه * `13` - درخواست بازگشت وجه به مشتری به دلیل درخواست مشتری * `14` - درخواست بازگشت وجه به فروشگاه پس از عدم تأیید توسط فروشگاه * `15` - درخواست بازگشت وجه به مشتری پس از ناموفق بودن توسط فروشگاه * `16` - بازپرداخت به فروشگاه پس از لغو توسط فروشگاه * `17` - بازپرداخت تکمیل شد * `18` - زمان انقضا گذشته است * `19` - تحویل شده * `20` - جمع اوری شده و در حال ارسال
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `statusDisplay` - Human-readable status
        should("test statusDisplay") {
            // uncomment below to test the property
            //modelInstance.statusDisplay shouldBe ("TODO")
        }

    }
}
