/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.MerchantPaidOrderList

class MerchantPaidOrderListTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MerchantPaidOrderList
        //val modelInstance = MerchantPaidOrderList()

        // to test the property `orderUuid`
        should("test orderUuid") {
            // uncomment below to test the property
            //modelInstance.orderUuid shouldBe ("TODO")
        }

        // to test the property `merchantOrderId` - شناسه منحصر به فرد سفارش در سیستم فروشنده
        should("test merchantOrderId") {
            // uncomment below to test the property
            //modelInstance.merchantOrderId shouldBe ("TODO")
        }

        // to test the property `merchantUniqueId` - شناسه منحصر به فرد فروشنده برای تأیید سفارش
        should("test merchantUniqueId") {
            // uncomment below to test the property
            //modelInstance.merchantUniqueId shouldBe ("TODO")
        }

        // to test the property `paidAt`
        should("test paidAt") {
            // uncomment below to test the property
            //modelInstance.paidAt shouldBe ("TODO")
        }

        // to test the property `refundsAt`
        should("test refundsAt") {
            // uncomment below to test the property
            //modelInstance.refundsAt shouldBe ("TODO")
        }

    }
}
