/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.MerchantOrderRefundResponse
import bwdk_sdk.models.OrderStatusEnum

class MerchantOrderRefundResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MerchantOrderRefundResponse
        //val modelInstance = MerchantOrderRefundResponse()

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `orderUuid`
        should("test orderUuid") {
            // uncomment below to test the property
            //modelInstance.orderUuid shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `statusDisplay`
        should("test statusDisplay") {
            // uncomment below to test the property
            //modelInstance.statusDisplay shouldBe ("TODO")
        }

        // to test the property `refundReason`
        should("test refundReason") {
            // uncomment below to test the property
            //modelInstance.refundReason shouldBe ("TODO")
        }

    }
}
