/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.Merchant

class MerchantTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Merchant
        //val modelInstance = Merchant()

        // to test the property `domain`
        should("test domain") {
            // uncomment below to test the property
            //modelInstance.domain shouldBe ("TODO")
        }

        // to test the property `logo`
        should("test logo") {
            // uncomment below to test the property
            //modelInstance.logo shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
