/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.Option
import bwdk_sdk.models.TypeNameEnum

class OptionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Option
        //val modelInstance = Option()

        // to test the property `typeName` - نوع ویژگی محصول: رنگ، سایز، گارانتی، وزن یا سایر  * `color` - رنگ * `size` - اندازه * `warranty` - گارانتی * `weight` - وزن * `other` - سایر
        should("test typeName") {
            // uncomment below to test the property
            //modelInstance.typeName shouldBe ("TODO")
        }

        // to test the property `name` - نام ویژگی (مثلاً 'قرمز' برای رنگ قرمز، 'XL' برای سایز)
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property ``value`` - مقدار ویژگی (مثلاً '#FF0000' برای کد رنگ یا مقدار دیگر)
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `isColor` - اگر نوع ویژگی رنگ است درست است، وگرنه غلط
        should("test isColor") {
            // uncomment below to test the property
            //modelInstance.isColor shouldBe ("TODO")
        }

    }
}
