/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.OrderCreateResponse

class OrderCreateResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderCreateResponse
        //val modelInstance = OrderCreateResponse()

        // to test the property `orderStartUrl`
        should("test orderStartUrl") {
            // uncomment below to test the property
            //modelInstance.orderStartUrl shouldBe ("TODO")
        }

        // to test the property `orderUuid`
        should("test orderUuid") {
            // uncomment below to test the property
            //modelInstance.orderUuid shouldBe ("TODO")
        }

    }
}
