/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.OrderCreate
import bwdk_sdk.models.OrderItemCreate

class OrderCreateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderCreate
        //val modelInstance = OrderCreate()

        // to test the property `merchantOrderId` - شناسه منحصر به فرد این سفارش در سیستم فروشنده
        should("test merchantOrderId") {
            // uncomment below to test the property
            //modelInstance.merchantOrderId shouldBe ("TODO")
        }

        // to test the property `merchantUniqueId` - شناسه منحصر به فرد برای تأیید اصالت سفارش
        should("test merchantUniqueId") {
            // uncomment below to test the property
            //modelInstance.merchantUniqueId shouldBe ("TODO")
        }

        // to test the property `callbackUrl` - آدرس وب‌هوک برای دریافت اطلاع رسانی وضعیت پرداخت
        should("test callbackUrl") {
            // uncomment below to test the property
            //modelInstance.callbackUrl shouldBe ("TODO")
        }

        // to test the property `destinationAddress`
        should("test destinationAddress") {
            // uncomment below to test the property
            //modelInstance.destinationAddress shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `referenceCode` - کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX)
        should("test referenceCode") {
            // uncomment below to test the property
            //modelInstance.referenceCode shouldBe ("TODO")
        }

        // to test the property `mainAmount` - مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان)
        should("test mainAmount") {
            // uncomment below to test the property
            //modelInstance.mainAmount shouldBe ("TODO")
        }

        // to test the property `finalAmount` - مبلغ نهایی: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)
        should("test finalAmount") {
            // uncomment below to test the property
            //modelInstance.finalAmount shouldBe ("TODO")
        }

        // to test the property `totalPaidAmount` - مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)
        should("test totalPaidAmount") {
            // uncomment below to test the property
            //modelInstance.totalPaidAmount shouldBe ("TODO")
        }

        // to test the property `discountAmount` - مبلغ کل تخفیف برای تمام سفارش (به تومان)
        should("test discountAmount") {
            // uncomment below to test the property
            //modelInstance.discountAmount shouldBe ("TODO")
        }

        // to test the property `taxAmount` - مبلغ کل مالیات برای تمام سفارش (به تومان)
        should("test taxAmount") {
            // uncomment below to test the property
            //modelInstance.taxAmount shouldBe ("TODO")
        }

        // to test the property `shippingAmount` - هزینه ارسال برای سفارش (به تومان)
        should("test shippingAmount") {
            // uncomment below to test the property
            //modelInstance.shippingAmount shouldBe ("TODO")
        }

        // to test the property `loyaltyAmount` - مبلغ تخفیف باشگاه مشتریان/پاداش (به تومان)
        should("test loyaltyAmount") {
            // uncomment below to test the property
            //modelInstance.loyaltyAmount shouldBe ("TODO")
        }

        // to test the property `merchant` - مقدار توسط سیستم جایگذاری می شود
        should("test merchant") {
            // uncomment below to test the property
            //modelInstance.merchant shouldBe ("TODO")
        }

        // to test the property `sourceAddress` - مقدار توسط سیستم جایگذاری می شود
        should("test sourceAddress") {
            // uncomment below to test the property
            //modelInstance.sourceAddress shouldBe ("TODO")
        }

        // to test the property `reservationExpiredAt` - مهلت پرداخت (به عنوان Unix timestamp) قبل از اتمام سفارش
        should("test reservationExpiredAt") {
            // uncomment below to test the property
            //modelInstance.reservationExpiredAt shouldBe ("TODO")
        }

        // to test the property `preparationTime` - Preparation time for the order (in days)
        should("test preparationTime") {
            // uncomment below to test the property
            //modelInstance.preparationTime shouldBe ("TODO")
        }

        // to test the property `weight` - Total Weight of the order (in grams)
        should("test weight") {
            // uncomment below to test the property
            //modelInstance.weight shouldBe ("TODO")
        }

    }
}
