/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.OrderItemCreate
import bwdk_sdk.models.Option

class OrderItemCreateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderItemCreate
        //val modelInstance = OrderItemCreate()

        // to test the property `name` - نام کامل محصول شامل تمام مشخصات
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `count` - تعداد واحدهای این کالا در سفارش
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `options`
        should("test options") {
            // uncomment below to test the property
            //modelInstance.options shouldBe ("TODO")
        }

        // to test the property `primaryAmount` - قیمت اولیه برای هر واحد بدون تخفیف (به تومان)
        should("test primaryAmount") {
            // uncomment below to test the property
            //modelInstance.primaryAmount shouldBe ("TODO")
        }

        // to test the property `amount` - قیمت نهایی برای تمام واحدها بعد از تخفیف (به تومان)
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `discountAmount` - مبلغ کل تخفیف برای این کالا (به تومان)
        should("test discountAmount") {
            // uncomment below to test the property
            //modelInstance.discountAmount shouldBe ("TODO")
        }

        // to test the property `taxAmount` - مبلغ کل مالیات برای این کالا (به تومان)
        should("test taxAmount") {
            // uncomment below to test the property
            //modelInstance.taxAmount shouldBe ("TODO")
        }

        // to test the property `imageLink` - آدرس تصویر محصول
        should("test imageLink") {
            // uncomment below to test the property
            //modelInstance.imageLink shouldBe ("TODO")
        }

        // to test the property `preparationTime` - Preparation time for the item (in days)
        should("test preparationTime") {
            // uncomment below to test the property
            //modelInstance.preparationTime shouldBe ("TODO")
        }

        // to test the property `weight` - Weight of the item (in grams)
        should("test weight") {
            // uncomment below to test the property
            //modelInstance.weight shouldBe ("TODO")
        }

    }
}
