/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.OrderDetail
import bwdk_sdk.models.Merchant
import bwdk_sdk.models.OrderItemCreate
import bwdk_sdk.models.OrderStatusEnum
import bwdk_sdk.models.OrderUser
import bwdk_sdk.models.Packing
import bwdk_sdk.models.PaymentOrder
import bwdk_sdk.models.ShippingMethod

class OrderDetailTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderDetail
        //val modelInstance = OrderDetail()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `orderUuid`
        should("test orderUuid") {
            // uncomment below to test the property
            //modelInstance.orderUuid shouldBe ("TODO")
        }

        // to test the property `reservationExpiredAt` - Unix timestamp تا زمانی که سفارش برای پرداخت رزرو شده است
        should("test reservationExpiredAt") {
            // uncomment below to test the property
            //modelInstance.reservationExpiredAt shouldBe ("TODO")
        }

        // to test the property `merchantOrderId` - شناسه منحصر به فرد سفارش در سیستم فروشنده
        should("test merchantOrderId") {
            // uncomment below to test the property
            //modelInstance.merchantOrderId shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `statusDisplay`
        should("test statusDisplay") {
            // uncomment below to test the property
            //modelInstance.statusDisplay shouldBe ("TODO")
        }

        // to test the property `mainAmount` - مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان)
        should("test mainAmount") {
            // uncomment below to test the property
            //modelInstance.mainAmount shouldBe ("TODO")
        }

        // to test the property `finalAmount` - قیمت نهایی قابل پرداخت توسط مشتری: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)
        should("test finalAmount") {
            // uncomment below to test the property
            //modelInstance.finalAmount shouldBe ("TODO")
        }

        // to test the property `totalPaidAmount` - مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)
        should("test totalPaidAmount") {
            // uncomment below to test the property
            //modelInstance.totalPaidAmount shouldBe ("TODO")
        }

        // to test the property `discountAmount` - کل تخفیف اعمال شده بر سفارش (به تومان)
        should("test discountAmount") {
            // uncomment below to test the property
            //modelInstance.discountAmount shouldBe ("TODO")
        }

        // to test the property `taxAmount` - مبلغ کل مالیات برای سفارش (به تومان)
        should("test taxAmount") {
            // uncomment below to test the property
            //modelInstance.taxAmount shouldBe ("TODO")
        }

        // to test the property `shippingAmount` - هزینه ارسال برای سفارش (به تومان)
        should("test shippingAmount") {
            // uncomment below to test the property
            //modelInstance.shippingAmount shouldBe ("TODO")
        }

        // to test the property `loyaltyAmount` - مقدار تخفیف از برنامه باشگاه مشتریان/پاداش (به تومان)
        should("test loyaltyAmount") {
            // uncomment below to test the property
            //modelInstance.loyaltyAmount shouldBe ("TODO")
        }

        // to test the property `callbackUrl` - آدرسی برای دریافت اطلاع رسانی وضعیت پرداخت پس از تکمیل سفارش
        should("test callbackUrl") {
            // uncomment below to test the property
            //modelInstance.callbackUrl shouldBe ("TODO")
        }

        // to test the property `merchant`
        should("test merchant") {
            // uncomment below to test the property
            //modelInstance.merchant shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `sourceAddress`
        should("test sourceAddress") {
            // uncomment below to test the property
            //modelInstance.sourceAddress shouldBe ("TODO")
        }

        // to test the property `destinationAddress`
        should("test destinationAddress") {
            // uncomment below to test the property
            //modelInstance.destinationAddress shouldBe ("TODO")
        }

        // to test the property `selectedShippingMethod`
        should("test selectedShippingMethod") {
            // uncomment below to test the property
            //modelInstance.selectedShippingMethod shouldBe ("TODO")
        }

        // to test the property `shippingSelectedAt`
        should("test shippingSelectedAt") {
            // uncomment below to test the property
            //modelInstance.shippingSelectedAt shouldBe ("TODO")
        }

        // to test the property `addressSelectedAt`
        should("test addressSelectedAt") {
            // uncomment below to test the property
            //modelInstance.addressSelectedAt shouldBe ("TODO")
        }

        // to test the property `packingAmount` - هزینه روش بسته‌بندی انتخاب‌شده (به تومان)
        should("test packingAmount") {
            // uncomment below to test the property
            //modelInstance.packingAmount shouldBe ("TODO")
        }

        // to test the property `packingSelectedAt`
        should("test packingSelectedAt") {
            // uncomment below to test the property
            //modelInstance.packingSelectedAt shouldBe ("TODO")
        }

        // to test the property `selectedPacking`
        should("test selectedPacking") {
            // uncomment below to test the property
            //modelInstance.selectedPacking shouldBe ("TODO")
        }

        // to test the property `canSelectPacking`
        should("test canSelectPacking") {
            // uncomment below to test the property
            //modelInstance.canSelectPacking shouldBe ("TODO")
        }

        // to test the property `canSelectShipping`
        should("test canSelectShipping") {
            // uncomment below to test the property
            //modelInstance.canSelectShipping shouldBe ("TODO")
        }

        // to test the property `canSelectAddress`
        should("test canSelectAddress") {
            // uncomment below to test the property
            //modelInstance.canSelectAddress shouldBe ("TODO")
        }

        // to test the property `canProceedToPayment`
        should("test canProceedToPayment") {
            // uncomment below to test the property
            //modelInstance.canProceedToPayment shouldBe ("TODO")
        }

        // to test the property `isPaid`
        should("test isPaid") {
            // uncomment below to test the property
            //modelInstance.isPaid shouldBe ("TODO")
        }

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `payment`
        should("test payment") {
            // uncomment below to test the property
            //modelInstance.payment shouldBe ("TODO")
        }

        // to test the property `preparationTime` - زمان آمادهسازی سفارش (به روز)
        should("test preparationTime") {
            // uncomment below to test the property
            //modelInstance.preparationTime shouldBe ("TODO")
        }

        // to test the property `weight` - وزن کل سفارش (بر حسب گرم)
        should("test weight") {
            // uncomment below to test the property
            //modelInstance.weight shouldBe ("TODO")
        }

        // to test the property `selectedShippingData`
        should("test selectedShippingData") {
            // uncomment below to test the property
            //modelInstance.selectedShippingData shouldBe ("TODO")
        }

        // to test the property `referenceCode` - کد مرجع منحصر به فرد برای پیگیری سفارش مشتری (فرمت: BD-XXXXXXXX)
        should("test referenceCode") {
            // uncomment below to test the property
            //modelInstance.referenceCode shouldBe ("TODO")
        }

        // to test the property `promotionDiscountAmount`
        should("test promotionDiscountAmount") {
            // uncomment below to test the property
            //modelInstance.promotionDiscountAmount shouldBe ("TODO")
        }

        // to test the property `promotionData`
        should("test promotionData") {
            // uncomment below to test the property
            //modelInstance.promotionData shouldBe ("TODO")
        }

        // to test the property `digipayMarkupAmount` - مبلغ نشانه‌گذاری برای سفارش (به تومان)
        should("test digipayMarkupAmount") {
            // uncomment below to test the property
            //modelInstance.digipayMarkupAmount shouldBe ("TODO")
        }

        // to test the property `markupCommissionPercentage` - درصد کمیسیون نشانه‌گذاری برای سفارش (به درصد)
        should("test markupCommissionPercentage") {
            // uncomment below to test the property
            //modelInstance.markupCommissionPercentage shouldBe ("TODO")
        }

        // to test the property `previousStatus`
        should("test previousStatus") {
            // uncomment below to test the property
            //modelInstance.previousStatus shouldBe ("TODO")
        }

        // to test the property `previousStatusDisplay`
        should("test previousStatusDisplay") {
            // uncomment below to test the property
            //modelInstance.previousStatusDisplay shouldBe ("TODO")
        }

    }
}
