/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.PaginatedOrderDetailList
import bwdk_sdk.models.OrderDetail

class PaginatedOrderDetailListTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaginatedOrderDetailList
        //val modelInstance = PaginatedOrderDetailList()

        // to test the property `results`
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

        // to test the property `next`
        should("test next") {
            // uncomment below to test the property
            //modelInstance.next shouldBe ("TODO")
        }

        // to test the property `previous`
        should("test previous") {
            // uncomment below to test the property
            //modelInstance.previous shouldBe ("TODO")
        }

    }
}
