/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.PaymentOrder
import bwdk_sdk.models.GatewayTypeEnum

class PaymentOrderTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentOrder
        //val modelInstance = PaymentOrder()

        // to test the property `finalAmount`
        should("test finalAmount") {
            // uncomment below to test the property
            //modelInstance.finalAmount shouldBe ("TODO")
        }

        // to test the property `gatewayType`
        should("test gatewayType") {
            // uncomment below to test the property
            //modelInstance.gatewayType shouldBe ("TODO")
        }

        // to test the property `gatewayTypeDisplay`
        should("test gatewayTypeDisplay") {
            // uncomment below to test the property
            //modelInstance.gatewayTypeDisplay shouldBe ("TODO")
        }

        // to test the property `paidAt`
        should("test paidAt") {
            // uncomment below to test the property
            //modelInstance.paidAt shouldBe ("TODO")
        }

        // to test the property `gatewayName`
        should("test gatewayName") {
            // uncomment below to test the property
            //modelInstance.gatewayName shouldBe ("TODO")
        }

        // to test the property `invoiceId`
        should("test invoiceId") {
            // uncomment below to test the property
            //modelInstance.invoiceId shouldBe ("TODO")
        }

        // to test the property `settlementDate`
        should("test settlementDate") {
            // uncomment below to test the property
            //modelInstance.settlementDate shouldBe ("TODO")
        }

        // to test the property `settlementStatus`
        should("test settlementStatus") {
            // uncomment below to test the property
            //modelInstance.settlementStatus shouldBe ("TODO")
        }

        // to test the property `settlementStatusDisplay`
        should("test settlementStatusDisplay") {
            // uncomment below to test the property
            //modelInstance.settlementStatusDisplay shouldBe ("TODO")
        }

    }
}
