/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.ReviveShipment

class ReviveShipmentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReviveShipment
        //val modelInstance = ReviveShipment()

        // to test the property `preparationTime` - زمان آمادهسازی سفارش (به روز)
        should("test preparationTime") {
            // uncomment below to test the property
            //modelInstance.preparationTime shouldBe ("TODO")
        }

    }
}
