/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.ShippingMethod
import bwdk_sdk.models.BusinessAddress
import bwdk_sdk.models.DeliveryTimeRangeDisplay
import bwdk_sdk.models.ShippingTypeEnum

class ShippingMethodTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShippingMethod
        //val modelInstance = ShippingMethod()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - نام روش/گزینه بسته‌بندی
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `getShippingTypeDisplay`
        should("test getShippingTypeDisplay") {
            // uncomment below to test the property
            //modelInstance.getShippingTypeDisplay shouldBe ("TODO")
        }

        // to test the property `shippingTypeDisplay`
        should("test shippingTypeDisplay") {
            // uncomment below to test the property
            //modelInstance.shippingTypeDisplay shouldBe ("TODO")
        }

        // to test the property `deliveryTimeDisplay`
        should("test deliveryTimeDisplay") {
            // uncomment below to test the property
            //modelInstance.deliveryTimeDisplay shouldBe ("TODO")
        }

        // to test the property `deliveryTimeRangeDisplay`
        should("test deliveryTimeRangeDisplay") {
            // uncomment below to test the property
            //modelInstance.deliveryTimeRangeDisplay shouldBe ("TODO")
        }

        // to test the property `inventoryAddress`
        should("test inventoryAddress") {
            // uncomment below to test the property
            //modelInstance.inventoryAddress shouldBe ("TODO")
        }

        // to test the property `description` - شناسه روش ارسال برای استفاده در سفارش
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `shippingType` - شناسه وضعیت ارسال از دیجی اکسپرس  * `1` - سایر * `2` - دیجی اکسپرس
        should("test shippingType") {
            // uncomment below to test the property
            //modelInstance.shippingType shouldBe ("TODO")
        }

        // to test the property `cost` - هزینه ارسال برای منطقه اصلی (مثلاً تهران) به تومان
        should("test cost") {
            // uncomment below to test the property
            //modelInstance.cost shouldBe ("TODO")
        }

        // to test the property `secondaryCost` - هزینه ارسال برای مناطق دیگر به تومان
        should("test secondaryCost") {
            // uncomment below to test the property
            //modelInstance.secondaryCost shouldBe ("TODO")
        }

        // to test the property `minimumTimeSending` - حداقل تعداد روز از تاریخ سفارش تا تحویل
        should("test minimumTimeSending") {
            // uncomment below to test the property
            //modelInstance.minimumTimeSending shouldBe ("TODO")
        }

        // to test the property `maximumTimeSending` - Maximum number of days from order date to delivery
        should("test maximumTimeSending") {
            // uncomment below to test the property
            //modelInstance.maximumTimeSending shouldBe ("TODO")
        }

        // to test the property `isPayAtDestination` - آیا روش ارسال پرداخت در مقصد است
        should("test isPayAtDestination") {
            // uncomment below to test the property
            //modelInstance.isPayAtDestination shouldBe ("TODO")
        }

    }
}
