/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.VerifyOrder

class VerifyOrderTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VerifyOrder
        //val modelInstance = VerifyOrder()

        // to test the property `merchantUniqueId` - شناسه منحصر به فرد ارسال شده هنگام ساخت سفارش برای تأیید اصالت سفارش
        should("test merchantUniqueId") {
            // uncomment below to test the property
            //modelInstance.merchantUniqueId shouldBe ("TODO")
        }

    }
}
