/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package bwdk_sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bwdk_sdk.models.WalletBalance

class WalletBalanceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WalletBalance
        //val modelInstance = WalletBalance()

        // to test the property `negativeSettlementDeadline` - مهلت تسویه تراز منفی
        should("test negativeSettlementDeadline") {
            // uncomment below to test the property
            //modelInstance.negativeSettlementDeadline shouldBe ("TODO")
        }

        // to test the property `amount` - موجودی کیف پول فعلی (برحسب تومان)
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

    }
}
